# Generated by Django 5.2.11 on 2026-02-12 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('graduation_date', models.DateField()),
                ('image', models.FileField(upload_to='diplomas/')),
                ('ipfs_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('token_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
