# Generated by Django 6.0.3 on 2026-03-10 13:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_diplomas', models.IntegerField(help_text='-1 signifie illimité')),
                ('level', models.IntegerField(help_text='Niveau pour contrôler les upgrades (plus grand = meilleur)')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('graduation_date', models.DateField()),
                ('image', models.FileField(upload_to='diplomas/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validé par tous'), ('REJECTED', 'Rejeté'), ('REVOKED', 'Révoqué')], default='PENDING', max_length=20)),
                ('school_validated', models.BooleanField(default=False)),
                ('school_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rectorate_validated', models.BooleanField(default=False)),
                ('rectorate_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rectorate_email_snapshot', models.EmailField(blank=True, max_length=254, null=True)),
                ('diploma_hash', models.CharField(blank=True, help_text='SHA-256 pseudonymisé des données clés (préfixé 0x) – jamais de données perso en clair', max_length=66, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Hash de la transaction Ethereum', max_length=66, null=True)),
                ('blockchain_status', models.CharField(choices=[('NOT_ANCHORED', 'Non ancré'), ('ANCHORED', 'Ancré sur la blockchain'), ('FAILED', "Échec d'ancrage"), ('REVOKED', 'Révoqué sur la blockchain')], default='NOT_ANCHORED', max_length=20)),
                ('expiry_date', models.DateField(blank=True, help_text="Date d'expiration du diplôme (laisser vide si le diplôme n'expire jamais).", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rectorate_email', models.EmailField(max_length=254, verbose_name='Email du Rectorat de rattachement')),
                ('subscription_start', models.DateField(default=django.utils.timezone.now)),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Consentement RGPD')),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du consentement RGPD')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='diplomas.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
