# Generated by Django 6.0.3 on 2026-03-12 07:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_diplomas', models.IntegerField(help_text='-1 signifie illimité')),
                ('level', models.IntegerField(help_text='Niveau pour contrôler les upgrades (plus grand = meilleur)')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date de naissance (identification visuelle anti-usurpation)', null=True)),
                ('course_name', models.CharField(max_length=200)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('image', models.FileField(help_text='Fichier du diplôme (PDF, image…)', upload_to='diplomas/')),
                ('photo', models.FileField(blank=True, help_text="Photo d'identité de l’étudiant (JPG, PNG…)", null=True, upload_to='photos/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('VALIDATED', 'Validé par tous'), ('REJECTED', 'Rejeté'), ('REVOKED', 'Révoqué')], default='PENDING', max_length=20)),
                ('school_validated', models.BooleanField(default=False)),
                ('school_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rectorate_validated', models.BooleanField(default=False)),
                ('rectorate_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rectorate_email_snapshot', models.EmailField(blank=True, max_length=254, null=True)),
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_deletion_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_email', models.EmailField(blank=True, help_text="Email étudiant (envoi code OTP droit à l'oubli uniquement)", max_length=254, null=True)),
                ('erasure_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('erasure_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('diploma_hash', models.CharField(blank=True, help_text='SHA-256 pseudonymisé des données clés (préfixé 0x) – jamais de données perso en clair', max_length=66, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Hash de la transaction Ethereum', max_length=66, null=True)),
                ('blockchain_status', models.CharField(choices=[('NOT_ANCHORED', 'Non ancré'), ('ANCHORED', 'Ancré sur la blockchain'), ('FAILED', "Échec d'ancrage"), ('REVOKED', 'Révoqué sur la blockchain')], default='NOT_ANCHORED', max_length=20)),
                ('school_eth_address', models.CharField(blank=True, help_text="Adresse MetaMask de l'école", max_length=42, null=True)),
                ('school_eth_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('rectorate_eth_address', models.CharField(blank=True, help_text='Adresse MetaMask du rectorat', max_length=42, null=True)),
                ('rectorate_eth_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text="Date d'expiration du diplôme. Null = n'expire jamais.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rectorate_email', models.EmailField(max_length=254, verbose_name='Email du Rectorat de rattachement')),
                ('subscription_start', models.DateField(default=django.utils.timezone.now)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom officiel de l'établissement")),
                ('school_type', models.CharField(blank=True, choices=[('LYCEE', 'Lycée'), ('BTS_IUT', 'BTS / IUT'), ('UNIVERSITE', 'Université'), ('GRANDE_ECOLE', 'Grande École'), ('INGENIEUR', "École d'ingénieurs"), ('COMMERCE', 'École de commerce'), ('AUTRE', 'Autre')], max_length=50, null=True, verbose_name="Type d'établissement")),
                ('school_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse postale')),
                ('school_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('school_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('school_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('school_website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('director_name', models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom du directeur / chef d'établissement")),
                ('uai_code', models.CharField(blank=True, help_text='7 chiffres + 1 lettre, ex : 0750654E', max_length=8, null=True, verbose_name='Code UAI/RNE')),
                ('siret', models.CharField(blank=True, help_text='14 chiffres', max_length=14, null=True, verbose_name='Numéro SIRET')),
                ('school_eth_address', models.CharField(blank=True, help_text="Adresse MetaMask officielle de l'école (0x...)", max_length=42, null=True)),
                ('rectorate_eth_address', models.CharField(blank=True, help_text='Adresse MetaMask officielle du rectorat (0x...', max_length=42, null=True)),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Consentement RGPD')),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du consentement RGPD')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='diplomas.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
