name: CI Quality Tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-quality:
    name: Backend (Django) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Certichain/certichain-back

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5   
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Tests Django
        run: python manage.py test
        env:
          SECRET_KEY: 'test-secret-key-pour-ci'
          DEBUG: 'True'

  frontend-quality:
    name: Frontend (React) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Certichain/certichain-front

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Installation des dépendances
        run: npm install

      - name: Build de test (Vérifie que React compile)
        run: npm run build
        env :
          CI: 'false'
